# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: admin
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  servlet:
    context-path: /api