DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id VARCHAR(20) NOT NULL COMMENT '主键ID-学工号',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    password VARCHAR(50) NOT NULL COMMENT '密码',
    permission VARCHAR(30) NULL DEFAULT NULL COMMENT '权限身份',
    department VARCHAR(100) NULL DEFAULT NULL COMMENT '学院',
    major VARCHAR(100) NULL DEFAULT NULL COMMENT '专业',
    administrativeClass VARCHAR(20) NULL DEFAULT NULL COMMENT '班级',
    phone VARCHAR(20) NULL DEFAULT NULL COMMENT '电话号码',
    PRIMARY KEY (id)
);

CREATE TABLE monitor
(
    id VARCHAR(20) NOT NULL COMMENT '主键ID-学工号',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    password VARCHAR(50) NOT NULL COMMENT '密码',
    department VARCHAR(100) NULL DEFAULT NULL COMMENT '学院',
    phoneNumber VARCHAR(30) NULL DEFAULT NULL COMMENT '电话号码',
    authorization VARCHAR(30) NULL DEFAULT NULL COMMENT '权限身份',
    PRIMARY KEY (id)
);

CREATE TABLE people
(
    id VARCHAR(20) NOT NULL COMMENT '主键ID-学工号',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    identity VARCHAR(20) NULL DEFAULT NULL COMMENT '身份',
    grade VARCHAR(5) NULL DEFAULT NULL COMMENT '年级',
    department VARCHAR(100) NULL DEFAULT NULL COMMENT '学院',
    major VARCHAR(100) NULL DEFAULT NULL COMMENT '专业',
    _class VARCHAR(50) NULL DEFAULT NULL COMMENT '班级',
    phoneNumber VARCHAR(30) NULL DEFAULT NULL COMMENT '电话号码',
    nucleic VARCHAR(30) NULL DEFAULT NULL COMMENT '核酸检测完成情况',
    healthyCode VARCHAR(100) NULL DEFAULT NULL COMMENT '健康码',
    campus VARCHAR(100) NULL DEFAULT NULL COMMENT '校区',
    date VARCHAR(15) NULL DEFAULT NULL COMMENT '最近检测日期',
    PRIMARY KEY (id)
)

CREATE TABLE message
(
    userid VARCHAR(20) NOT NULL COMMENT '用户ID',
    msgid VARCHAR(20) NOT NULL COMMENT '消息ID',
    title VARCHAR(20) NULL DEFAULT NULL COMMENT '消息标题',
    date VARCHAR(30) NULL DEFAULT NULL COMMENT '消息时间',
    detail VARCHAR(100) NULL DEFAULT NULL COMMENT '消息内容',
    read VARCHAR(5) not NULL DEFAULT 'false' COMMENT '是否已读'
)