DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id VARCHAR(20) NOT NULL COMMENT '主键ID-学工号',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    password VARCHAR(50) NOT NULL COMMENT '密码',
    identity VARCHAR(20) NULL DEFAULT NULL COMMENT '身份',
    permission VARCHAR(30) NULL DEFAULT NULL COMMENT '权限身份',
    department VARCHAR(100) NULL DEFAULT NULL COMMENT '学院',
    major VARCHAR(100) NULL DEFAULT NULL COMMENT '专业',
    grade VARCHAR(5) NULL DEFAULT NULL COMMENT '年级',
    administrativeClass VARCHAR(20) NULL DEFAULT NULL COMMENT '班级',
    campus VARCHAR(50) NULL DEFAULT NULL COMMENT '校区',
    phone VARCHAR(20) NULL DEFAULT NULL COMMENT '电话号码',
    code VARCHAR(2) NULL DEFAULT NULL COMMENT '通行码',
    healthyCode VARCHAR(100) NULL DEFAULT NULL COMMENT '健康码',
    attend BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否已打卡',
    nucleic VARCHAR(30) NULL DEFAULT NULL COMMENT '核酸检测完成情况',
    date VARCHAR(15) NULL DEFAULT NULL COMMENT '最近检测日期',
    PRIMARY KEY (id)
);

CREATE TABLE monitor
(
    id VARCHAR(20) NOT NULL COMMENT '主键ID-学工号',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    password VARCHAR(50) NOT NULL COMMENT '密码',
    department VARCHAR(100) NULL DEFAULT NULL COMMENT '学院',
    phoneNumber VARCHAR(30) NULL DEFAULT NULL COMMENT '电话号码',
    authorization VARCHAR(30) NULL DEFAULT NULL COMMENT '权限身份',
    PRIMARY KEY (id)
);

-- CREATE TABLE people
-- (
--     id VARCHAR(20) NOT NULL COMMENT '主键ID-学工号',
--     name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
--     identity VARCHAR(20) NULL DEFAULT NULL COMMENT '身份',
--     grade VARCHAR(5) NULL DEFAULT NULL COMMENT '年级',
--     department VARCHAR(100) NULL DEFAULT NULL COMMENT '学院',
--     major VARCHAR(100) NULL DEFAULT NULL COMMENT '专业',
--     _class VARCHAR(50) NULL DEFAULT NULL COMMENT '班级',
--     phoneNumber VARCHAR(30) NULL DEFAULT NULL COMMENT '电话号码',
--     nucleic VARCHAR(30) NULL DEFAULT NULL COMMENT '核酸检测完成情况',
--     healthyCode VARCHAR(100) NULL DEFAULT NULL COMMENT '健康码',
--     campus VARCHAR(50) NULL DEFAULT NULL COMMENT '校区',
--     date VARCHAR(15) NULL DEFAULT NULL COMMENT '最近检测日期',
--     PRIMARY KEY (id)
-- );

CREATE TABLE message
(
    userid VARCHAR(20) NOT NULL COMMENT '用户ID',
    msgid VARCHAR(20) NOT NULL COMMENT '消息ID',
    title VARCHAR(20) NULL DEFAULT NULL COMMENT '消息标题',
    date VARCHAR(30) NULL DEFAULT NULL COMMENT '消息时间',
    detail VARCHAR(100) NULL DEFAULT NULL COMMENT '消息内容',
    read BOOLEAN not NULL DEFAULT FALSE COMMENT '是否已读',
    PRIMARY KEY (msgid)
);

CREATE TABLE nucleic
(
    form_id VARCHAR(50) NOT NULL COMMENT '主键ID-表单ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    staff_id VARCHAR(50) NOT NULL COMMENT '学工号',
    app_date VARCHAR(50) NULL DEFAULT NULL COMMENT '预约日期',
    app_time INT NULL DEFAULT NULL COMMENT '预约时间(1/2/3/4代表四个时间段)',
    app_address VARCHAR(50) NULL DEFAULT NULL COMMENT '预约检查点',
    telenum VARCHAR(30) NULL DEFAULT NULL COMMENT '电话号码',
    email VARCHAR(80) NULL DEFAULT NULL COMMENT '电子邮箱',
    campus VARCHAR(30) NULL DEFAULT NULL COMMENT '所在校区',
    result INT NULL DEFAULT NULL COMMENT '0阴性，1阳性，2未知',
    PRIMARY KEY (form_id)
);

-- 打卡表单
CREATE TABLE punch
(
    id VARCHAR(20) NOT NULL COMMENT '主键ID-学工号',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    date VARCHAR(20) NULL DEFAULT NULL COMMENT '日期',
    campus VARCHAR(50) NULL DEFAULT NULL COMMENT '校区',
    region VARCHAR(50) NULL DEFAULT NULL COMMENT '地区',
    onCampus BOOLEAN NULL DEFAULT NULL COMMENT '是否在校',
    codeStatus VARCHAR(2) NULL DEFAULT NULL COMMENT '通行码状态',
    fever BOOLEAN NULL DEFAULT NULL COMMENT '是否发烧',
    control BOOLEAN NULL DEFAULT NULL COMMENT '是否在控制区',
    contact BOOLEAN NULL DEFAULT NULL COMMENT '是否密接',
    status BOOLEAN NULL DEFAULT NULL COMMENT '是否已打卡',
    PRIMARY KEY (id)
);

-- 审批表单
CREATE TABLE form
(
    form_id VARCHAR(50) NOT NULL COMMENT '表单 ID',
    staff_id VARCHAR(30) NOT NULL COMMENT '学工号',
    audit_id VARCHAR(30) NULL DEFAULT NULL COMMENT '审批人 ID',
    form_type VARCHAR(30) NULL DEFAULT NULL COMMENT '表单类型',
    status VARCHAR(30) DEFAULT '等待审核' COMMENT '表单状态',
    content VARCHAR(3000) NULL DEFAULT NULL COMMENT '表单内容',
    application_time VARCHAR(50) DEFAULT NULL COMMENT '申请时间',
    PRIMARY KEY (form_id)
);
